{
    "cookies": [
        "has given you a big chocolate cookie!yummmy :cookie:",
        "has given you a good homemade cookie! :cookie:",
        "has given you a plain, dry, old cookie. It was the last one in the bag. Gross. :cookie:",
        "gives you a sugar cookie. What, no frosting and sprinkles? 0\/10 would not touch. :cookie:",
        "gives you a chocolate chip cookie. Oh wait, those are raisins. Bleck! :cookie:",
        "gives you an enormous cookie. Poking it gives you more cookies. Weird. :cookie:",
        "gives you a fortune cookie. It reads \"Why aren't you working on any projects?\"",
        "gives you a fortune cookie. It reads \"Give that special someone a compliment\"",
        "gives you a fortune cookie. It reads \"Take a risk!\"",
        "gives you a fortune cookie. It reads \"Go outside.\"",
        "gives you a fortune cookie. It reads \"Don't forget to eat your veggies!\"",
        "gives you a fortune cookie. It reads \"Do you even lift?\"",
        "gives you a fortune cookie. It reads \"m808 pls\"",
        "gives you a fortune cookie. It reads \"If you move your hips, you'll get all the ladies.\"",
        "gives you a fortune cookie. It reads \"I love you.\"",
        "gives you a Golden Cookie. You can't eat it because it is made of gold. Dammit.",
        "gives you an Oreo cookie with a glass of milk!",
        "gives you a rainbow cookie made with love :heart:",
        "gives you an old cookie that was left out in the rain, it's moldy.",
        "bakes you fresh cookies, it smells amazing."
    ],
    "balls": [
        "Let me think..mmm ",
        "Yes.",
        "Reply hazy, try again.",
        "Without a doubt.",
        "Im saying no",
        "As I see it, yes.",
        "You may rely on it.",
        "Think about the question again and ask again.",
        "Outlook not so good.",
        "It is decidedly so i dont know",
        "Better not tell you now. That would be good.",
        "Very doubtful.",
        "Yes - definitely.",
        "It is certain.",
        "Cannot predict now.",
        "Most likely.",
        "ask me later, sorry.",
        "Nope.",
        "Outlook good.",
        "Don't count on it.",
        "Yes, in due time.",
        "NO!!! Definitely.",
        "You will have to wait.",
        "I have my doubts.",
        "Outlook so so.",
        "Looks good to me!",
        "I dont know actually",
        "Looking good!",
        "I like pizza.",
        "Probably.",
        "Are you kidding me ?",
        "Don't bet on it.",
        "Forget about it. Thats not going to happend",
        "No , but i love Rohlik",
        "I think yes , but i will think about that."
    ],
    "nodatafound": "No data found.",
    "currentlang": "\/me Language currently set to: %%LANGUAGE%%",
    "langerror": "\/me The language you've selected isn't available. Please visit %%LINK%% to find a list of languages available.",
    "langset": "\/me Language now set to: %%LANGUAGE%%",
    "retrievingdata": "Retrieving previously stored data.",
    "datarestored": "Previously stored data successfully retrieved.",
    "greyuser": "Only managers can run mfebot",
    "bouncer": "I cant be alive if i will run as a bouncer.",
    "online": "\/me %%BOTNAME%% v%%VERSION%% online!",
    "welcome": "\/me Hello and welcome %%NAME%% in our community! :purple_heart: We are so glad, that you came here. Enjoy your stay. :blue_heart:",
    "welcomeback": "\/me Hello %%NAME%%! Welcome back! :purple_heart:",
    "songknown": "\/me @%%NAME%%, this song is in the DJ history.",
    "notavailable": "\/me @%%NAME%%, the song you played was not available.",
    "timelimit": "\/me @%%NAME%%, your song is longer than %%MAXLENGTH%% minutes, you need permission to play longer songs.",
    "permissionownsong": "\/me :up: @%%NAME%% has permission to play their own production!",
    "isblacklisted": "\/me This track is on the %%BLACKLIST%% blacklist! Skipping...",
    "isopen": "@djs The roulette is now open! Type !join to participate! (A game where a random participant is moved to a random position in the waitlist)",
    "winnerpicked": "Congratulations to winner! @%%NAME%% is going to position %%POSITION%%.",
    "ball": "\/me %%NAME%%'s question was: \"%%QUESTION%%\" and %%BOTNAME%%'s response is: \"%%RESPONSE%%\"",
    "notghosting": "[%%NAME1%%] %%NAME2%% is not ghosting.",
    "ghosting": "[%%NAME1%%] %%NAME2%% is either ghosting or not here.",
    "alreadyadding": "\/me User is already being added! Changed the desired position to %%POSITION%%.",
    "adding": "\/me Added @%%NAME%% to the queue. Current queue: %%POSITION%%.",
    "usernotfound": "\/me I cant find the user.",
    "notdisconnected": "\/me @%%NAME%% is not in my disconnect list.",
    "noposition": "\/me No last position known. The waitlist needs to update at least once to register a user's last position.",
    "toolongago": "\/me @%%NAME%%'s You have been disconnected for long time..You have been gone for: %%TIME%%.",
    "valid": "\/me @%%NAME%% You have been disconnected for %%TIME%% . Your spot was %%POSITION%%. Im moving you back hold on.",
    "caps": "\/me @%%NAME%%, unglue your capslock button please.",
    "askskip": "\/me @%%NAME%%, Please do not ask for skip, only me and moderator will decide,when we need to skip.",
    "spam": "\/me @%%NAME%%, Dont spam pleaseee. its so anoying..",
    "roomadvertising": "\/me @%%NAME%%, don't post links to other rooms please.",
    "adfly": "\/me @%%NAME%%, please change your autowoot program. We suggest PlugCubed: http:\/\/plugcubed.net\/",
    "validgiftags": "\/me [@%%NAME%%] http:\/\/i.giphy.com\/%%ID%%.gif [Tags: %%TAGS%%]",
    "invalidgiftags": "\/me [@%%NAME%%] Invalid tags, try something different. [Tags: %%TAGS%%]",
    "validgifrandom": "\/me [@%%NAME%%] http:\/\/i.giphy.com\/%%ID%%.gif [Random GIF]",
    "invalidgifrandom": "\/me [@%%NAME%%] Invalid request, please try again",
    "invalidtime": "\/me [@%%NAME%%] Invalid time specified.",
    "nouserspecified": "\/me [@%%NAME%%] No user specified.",
    "invaliduserspecified": "\/me [@%%NAME%%] Invalid user specified.",
    "nolistspecified": "\/me [@%%NAME%%] No list specified.",
    "invalidlistspecified": "\/me [@%%NAME%%] Invalid list specified.",
    "novaliduserspecified": "\/me [@%%NAME%%] No valid user specified.",
    "nolimitspecified": "\/me [@%%NAME%%] No limit specified.",
    "invalidlimitspecified": "\/me [@%%NAME%%] Invalid limit.",
    "invalidpositionspecified": "\/me [@%%NAME%%] Invalid position specified.",
    "whois": "\/me [%%NAME1%%] Username: %%NAME2%%, ID: %%ID%%, Rank: %%RANK%%, Joined: %%JOINED%%, Level: %%LEVEL%%, Language: %%LANGUAGE%%, Avatar: %%AVATAR%%, Profile: %%PROFILE%%",
    "toggleon": "\/me [@%%NAME%%] %%FUNCTION%% enabled.",
    "toggleoff": "\/me [@%%NAME%%] %%FUNCTION%% disabled.",
    "cmddeletion": "command deletion",
    "afkremoval": "AFK removal",
    "afksremoved": "AFK's removed",
    "afklimit": "AFK limit",
    "autodisable": "autodisable",
    "autoskip": "autoskip",
    "newblacklisted": "\/me [@%%NAME%%] This track belongs on the %%BLACKLIST%% blacklist! [ %%AUTHOR%% - %%TITLE%% - %%MID%% ]",
    "blinfo": "[@%%NAME%%] Blacklist Info - author: %%AUTHOR%%, title: %%TITLE%%, mid: %%SONGID%%",
    "blacklist": "blacklist",
    "cycleguard": "cycleguard",
    "timeguard": "timeguard",
    "chatfilter": "chatfilter",
    "historyskip": "historyskip",
    "lockdown": "lockdown",
    "lockguard": "lockguard",
    "usercommands": "usercommands",
    "motd": "MotD",
    "welcomemsg": "welcome message",
    "songstats": "song statistics",
    "etarestriction": "eta restriction",
    "voteskip": "voteskip",
    "voteskiplimit": "\/me [@%%NAME%%] Voteskip is now set for  %%LIMIT%% mehs.",
    "voteskipexceededlimit": "\/me @%%NAME%%, Your song has so much mehs. I need to skip you, sorry. (%%LIMIT%% mehs).",
    "voteskipinvalidlimit": "\/me [@%%NAME%%] Invalid voteskip limit, please try again using a number to signify the number of mehs.",
    "voteskipsetlimit": "\/me [@%%NAME%%] Voteskip limit set to %%LIMIT%%.",
    "activeusersintime": "\/me [@%%NAME%%] There have been %%AMOUNT%% users chatting in the past %%TIME%% minutes.",
    "maximumafktimeset": "\/me [@%%NAME%%] Maximum afk duration set to %%TIME%% minutes.",
    "afkstatusreset": "\/me [@%%NAME%%] Reset the afk status of @%%USERNAME%%.",
    "inactivefor": "\/me [@%%NAME%%] @%%USERNAME%% has been inactive for %%TIME%%.",
    "inactivelonger": "\/me [@%%NAME%%] @%%USERNAME%% has been inactive longer than %%BOTNAME%%'s been online.",
    "autowoot": "\/me We recommend PlugCubed for autowooting: http:\/\/plugcubed.net\/",
    "brandambassador": "\/me A Brand Ambassador is the voice of the plug.dj users. They promote events, engage the community and share the plug.dj message around the world. For more info: https:\/\/plug.dj\/ba",
    "bouncerplusrank": "\/me [@%%NAME%%] You need to be manager if you want to enable Bouncer+",
    "chatcleared": "\/me [@%%NAME%%] Im clearing the chat",
    "deletechat": "\/me [@%%NAME%%] All messages of  %%USERNAME%% are deleted.",
    "commandslink": "\/me %%BOTNAME%% commands: %%LINK%%",
    "eatcookie": "\/me Im eating a cookie :cookie:",
    "nousercookie": "\/em I dont see %%NAME%% in the room so i will eat that cookie for him :cookie:",
    "selfcookie": "\/me @%%NAME%%, you're a bit greedy, aren't you? Giving cookies to yourself, bah. Share some with other people!",
    "cookie": "\/me @%%NAMETO%%, %%NAMEFROM%% %%COOKIE%%",
    "cycleguardtime": "\/me [@%%NAME%%] The cycleguard is set to %%TIME%% minute(s).",
    "dclookuprank": "\/me [@%%NAME%%] Only bouncers and above can do a lookup for others.",
    "emojilist": "\/me You can find list of all plug.dj emojis here: %%LINK%%",
    "notinwaitlist": "\/me @%%NAME%%, Sorry, but you are not in the waitlist",
    "youarenext": "\/me @%%NAME%%, you are DJing after this song.",
    "youaredj": "\/me @%%NAME%%, You are curently playing.",
    "eta": "\/me @%%NAME%%, your position in the waitlist is %%POSITION%% and you will reach the booth in approximately %%TIME%%.",
    "facebook": "\/me Like us on facebook: %%LINK%%",
    "starterhelp": "\/me This image will get you started on plug: %%LINK%%",
    "roulettejoin": "@%%NAME%% joined the roulette! Join too and win the price ! (!leave if you regret it)",
    "jointime": "\/me [@%%NAMEFROM%%] @%%USERNAME%% has been in the room for %%TIME%%.",
    "kickrank": "\/me [@%%NAME%%] you can't kick users with an equal or higher rank than you!",
    "kick": "\/me [@%%NAME%%], @%%USERNAME%% you are being kicked from the community for %%TIME%% minutes.",
    "kill": "\/me turning off...",
    "logout": "\/me [@%%NAME%%] Logging out %%BOTNAME%%",
    "rouletteleave": "\/me @%%NAME%% left the roulette!",
    "songlink": "\/me [@%%NAME%%] Link to current song: %%LINK%%",
    "usedlockskip": "\/me [%%NAME%% used lockskip]",
    "usedskip": "\/me [%%NAME%% used skip]",
    "skippos": "\/me [@%%NAME%%] DJs will now be moved to position %%POSITION%% when skipped.",
    "lockguardtime": "\/me [@%%NAME%%] The lockguard is set to %%TIME%% minute(s).",
    "maxlengthtime": "\/me [@%%NAME%%] The maximum song duration is set to %%TIME%% minutes.",
    "motdset": "\/me MotD set to:  %%MSG%%",
    "motdintervalset": "\/me MotD interval set to %%INTERVAL%%.",
    "currentbotname": "\/me My name is: %%BOTNAME%%",
    "botnameset": "\/me I have been renamed to: %%BOTNAME%%",
    "addbotwaitlist": "\/me @%%NAME%%, Im so happy that you wanted to add me in the waitlist, but im to shy so dont add me please.",
    "move": "\/me [%%NAME%% used move]",
    "mutednotime": "\/me [@%%NAME%%] Muted @%%USERNAME%%.",
    "mutedmaxtime": "\/me [@%%NAME%%] You can only mute for maximum %%TIME%% minutes.",
    "mutedtime": "\/me [@%%NAME%%] Muted @%%USERNAME%% for %%TIME%% minutes.",
    "unmuted": "\/me [@%%NAME%%] User @%%USERNAME%% is now unmuted.",
    "muterank": "\/me [@%%NAME%%] You can't mute persons with an equal or higher rank than you.",
    "oplist": "\/me OP list: %%LINK%%",
    "pong": "\/me Pooong!",
    "reload": "\/me Be right back.",
    "removenotinwl": "\/me [@%%NAME%%] This user called @%%USERNAME%% is not in the waitlist.",
    "roomrules": "\/me Please read our rules. You can find it here: %%LINK%%",
    "sessionstats": "\/me [@%%NAME%%] Total woots: %%WOOTS%%, total mehs: %%MEHS%%, total grabs: %%GRABS%%.",
    "forceskip": "\/me [%%NAME%% used forceskip]",
    "madeby": "\/me I was made by my dad %%NAME%%.",
    "activefor": "I have been active here for about %%TIME%%.",
    "swapinvalid": "\/me [@%%NAME%%] Invalid user specified. (names with spaces are not tolerated)",
    "swapwlonly": "\/me [@%%NAME%%] I can swap users only if they are in the waitlist!",
    "swapping": "\/me Swapping %%NAME1%% with %%NAME2%%.",
    "genres": "\/me Please find the permissible room genres here: %%LINK%%",
    "notbanned": "\/me [@%%NAME%%] the user which you are looking for is not banned.",
    "unmutedeveryone": "\/me [@%%NAME%%] Everyone is unmuted.",
    "unmuteeveryonerank": "\/me [@%%NAME%%] Only managers and up can unmute everyone at once.",
    "notmuted": "\/me [@%%NAME%%] I cant see this user in the mute list.",
    "unmuterank": "\/me [@%%NAME%%] You can't unmute persons with an equal or higher rank than you.",
    "commandscd": "\/me [@%%NAME%%] The cooldown for commands by users is now set to %%TIME%% seconds.",
    "voteratio": "\/me [@%%NAME%%] @%%USERNAME%% ~ woots: %%WOOT%%, mehs: %%MEHS%%, ratio (w\/m): %%RATIO%%.",
    "website": "\/me Visit our site: %%LINK%%",
    "youtube": "\/me [%%NAME%%] Subscribe to us on youtube: %%LINK%%",
    "songstatistics": "\/me %%ARTIST%% - %%TITLE%%: %%WOOTS%%:+1: | %%GRABS%%:star: | %%MEHS%%:-1:.",
    "thorNotClose": "\/me @%%NAME%%, you're not worthy of getting close to the hammer!",
    "thorcd": "\/me @%%NAME%% you can try to lift the hammer in %%TIME%% minutes.",
    "thorWorthy": "\/me @%%NAME%% you're worthy of the hammer :hammer:, congratulations!",
    "thorNotWorthy": "\/me @%%NAME%% you're not worthy of the hammer."
}
